---
- hosts: lab2.example.com
  become: yes
  gather_facts: no
  tasks:
  - name: delete all existing repo
    shell: rm /etc/yum.repos.d/*
    args: 
      warn: false

  - name: Add local epel repository
    yum_repository:
      name: localepel
      description: local EPEL YUM repo
      baseurl: ftp://192.168.122.1/pub/repo/centos7/epel/$releasever/$basearch/
      gpgcheck: no
      enabled: yes
      

  - name: Add local centos repository
    yum_repository:
      name: localcentos
      description: local Centos YUM repo
      baseurl: ftp://192.168.122.1/pub/repo/centos7/cdrom
      gpgcheck: no
      enabled: yes
      

  - name: yum-clean-metadata
    command: yum repolist
    args: 
      warn: false
    register: repolist

  - debug: var=repolist
