---
# Disk space allocated to the /tmp directory
#
#  At least 1 GB of space in the /tmp directory.

- name: Check size of /tmp
  shell: df --block-size=1G /tmp | awk 'END { print $4 }'
  register: tmpsize
  failed_when: tmpsize.stdout|int < 1