---
- hosts: centrale
  tasks:
  - name: get /etc/motd
    shell: cat /etc/motd
    register: motd_contents
  - debug: msg="stdout={{motd_contents}}"
  - debug: msg="MOTD is empty"
    when: motd_contents.stdout =="" # use of conditions
...
