cmd: "ansible-playbook"
name: "run playbook"
args:
   - "{FILE_ACTIVE}"
#   - "--tags={SELECTION}"
sh: true,
cwd: .
#env:
#   VARIABLE1: {FILE_ACTIVE}
#   VARIABLE2: "VALUE2"
# errorMatch:
#   - ^regexp1$
#   - ^regexp2$
# warningMatch:
#   - ^regexp1$
#   - ^regexp2$
# keymap: <keymap string>
# atomCommandName: namespace:command
# targets:
#   extraTargetName:
#       cmd: "<command to execute>"
#       args:
#       # (any previous options are viable here except `targets` itself)
