# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "oracle" do |oracle|
    oracle.vm.box = "centos/7"
    #oracle.vm.network "private_network", ip: "192.168.4.100"
    oracle.vm.hostname = "oracle.example.com"
    oracle.hostsupdater.aliases = ["oracle", "oracle.example.com"]
    #oracle.ssh.host = "192.168.4.100"
    oracle.vm.synced_folder '.', '/vagrant', disabled: true
    oracle.vm.provision "shell", inline: <<-SHELL
        sudo sed -i 's/PasswordAuthentication no/ PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sudo systemctl reload sshd
      SHELL
  end


  config.vm.provider "libvirt" do |v|
    v.memory = 4096
    v.cpus = 2
    v.storage :file,
      :device => 'vdb',  # automatically chosen if unspecified!
      :size => '10G',    # defaults to 10G if unspecified!
      :type => 'qcow2'    # defaults to 'qcow2' if unspecified!
    v.storage :file,
      :device => 'vdc',  # automatically chosen if unspecified!
      :size => '10G',    # defaults to 10G if unspecified!
      :type => 'qcow2'    # defaults to 'qcow2' if unspecified!
  end



  config.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  public_key = File.read("id_rsa.pub")
  config.vm.provision :shell, :inline =>"
     echo 'Copying ansible-vm public SSH Keys to the VM'
     mkdir -p /home/vagrant/.ssh
     chmod 700 /home/vagrant/.ssh
     echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
     chmod -R 600 /home/vagrant/.ssh/authorized_keys
     echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
     echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
     echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
     chmod -R 600 /home/vagrant/.ssh/config
     ", privileged: false
  config.hostsupdater.remove_on_suspend = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "hichtest.yaml"

  end
end
